name: dart_amqp_rpc
description: >
  An opionated library for performing RPC over AMQP using JSON, protocol buffers, msgpack
  or custom user-defined codecs
version: 0.0.1
author: Achilleas Anagnostopoulos
homepage: https://github.com/achilleasa/dart_amqp_rpc
dependencies:
  logging: ">=0.9.3 <0.10.0"
  uuid: ">= 0.5.0 < 0.6.0"
  dart_amqp: # ">0.0.1 < 0.1.0"
    git: git://github.com/achilleasa/dart_amqp.git
dev_dependencies:
  unittest: any
  protobuf: ">=0.3.5+3 <0.4.0"
  msgpack: ">=0.0.4 <0.1.0"
